project:
  type: book
  output-dir: docs

book:
  title: "Surface Hydrology"
  author: "Yair Mau"
  favicon: archive/cloud-rain.png
  # date: "10/18/2022"
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
        - introduction/introduction-lecture.qmd
        - introduction/introduction-exercises.ipynb
    - part: "Precipitation" #precipitation/precipitation.qmd
      chapters:
        - precipitation/interannual-lecture.qmd
        - precipitation/interannual-exercises.ipynb
        - precipitation/intra-annual-lecture.qmd
        - precipitation/intra-annual-exercises.ipynb
        - precipitation/return-period-lecture.qmd
        - precipitation/return-period-exercises.ipynb
    - part: "Evapotranspiration" #evapotranspiration/evapotranspiration.qmd
      chapters:
        - evapotranspiration/evapotranspiration-lecture.ipynb
        - evapotranspiration/evapotranspiration-exercises.ipynb
    - part: "Infiltration" #infiltration/infiltration.qmd
      chapters:
        - infiltration/infiltration-lecture.ipynb
        - infiltration/infiltration-exercises.ipynb
    - part: "Streamflow" #streamflow/streamflow.qmd
      chapters:
        - streamflow/streamflow-lecture.ipynb
        - streamflow/streamflow-exercises.ipynb
        - streamflow/unit-hydrograph-lecture.ipynb
    - part: "summing up" #summing-up/summing-up.qmd
      chapters:
        - summing-up/budyko-framework-lecture.ipynb
        - summing-up/spatial-distribution.ipynb
    - part: assignments/assignments-general.qmd
      chapters:
        - assignments/assignment1-precipitation.ipynb
        - assignments/assignment2-ET.ipynb
        - assignments/assignment3-streamflow.ipynb
        - assignments/assignment-FINAL.ipynb
    - part: appendix/index.qmd
      chapters:    
        - appendix/date_formatting.ipynb
    - summary.qmd
    - references.qmd
  # repo-url: https://github.com/agrotech-lab/my-book-test
  # repo-actions: [source]
  sidebar:
    logo: archive/cloud-rain.png
  #   style: "docked"
  #   collapse-level: 2


bibliography: references.bib

format:
  html:
    theme:
    - flatly
    - custom.scss
    css: styles.css
    fontsize: 1.2em
    highlight-style: breezedark
  pdf:
    documentclass: scrreprt



