project:
  type: book
  output-dir: docs

book:
  title: "Surface Hydrology"
  author: "Yair Mau"
  repo-url: https://github.com/yairmau/surface-hydrology/
  favicon: archive/cloud-rain.png
  # date: "10/18/2022"
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
        - introduction/introduction-lecture.qmd
        - introduction/introduction-exercises.ipynb
    - part: precipitation/precipitation.qmd
      chapters:
        - precipitation/intra-annual-lecture.ipynb
        - precipitation/intra-annual-exercises.ipynb
        - precipitation/interannual-lecture.ipynb
        - precipitation/interannual-exercises.ipynb
        - precipitation/return-period-lecture.ipynb
        - precipitation/return-period-exercises.ipynb
    - part: "Evapotranspiration" #evapotranspiration/evapotranspiration.qmd
      chapters:
        - evapotranspiration/evapotranspiration-lecture.qmd
        - evapotranspiration/evapotranspiration-exercises.ipynb
    - part: infiltration/infiltration.qmd
      chapters:
        - infiltration/infiltration-lecture.qmd
        - infiltration/infiltration-exercises.ipynb
    - part: "Streamflow" #streamflow/streamflow.qmd
      chapters:
        - streamflow/streamflow-lecture.ipynb
        - streamflow/streamflow-exercises.ipynb
        - streamflow/unit-hydrograph-lecture.ipynb
    - part: "summing up" #summing-up/summing-up.qmd
      chapters:
        - summing-up/budyko-framework-lecture.qmd
        - summing-up/spatial-distribution.qmd
    - part: assignments/assignments-general.qmd
      chapters:
        - assignments/assignment0-first-graphs.ipynb
        - assignments/assignment1-return-period.ipynb
        - assignments/assignment2-ET-NOAA.ipynb
        # - assignments/assignment2-ET.ipynb
        # - assignments/assignment3-streamflow.ipynb
        # - assignments/assignment-FINAL.ipynb
        # - assignments/assignment-FINAL2.qmd
    - part: appendix/index.qmd
      chapters:    
        - appendix/date_formatting.ipynb
        - appendix/plotting-guidelines.ipynb
    - summary.qmd
    - references.qmd
  # repo-url: https://github.com/agrotech-lab/my-book-test
  # repo-actions: [source]
  sidebar:
    tools:
      - icon: house
        href: https://yairmau.com/
    logo: archive/cloud-rain.png
  #   style: "docked"
  #   collapse-level: 2
  search: true


bibliography: references.bib

format:
  html:
    theme:
    - flatly
    - custom.scss
    css: styles.css
    fontsize: 1.2em
    highlight-style: breezedark
    code-line-numbers: true
    code-tools:
      source: repo  # https://quarto.org/docs/output-formats/html-code.html#code-tools
    callout-icon: false
    html-math-method: katex
    fig-align: center

  pdf:
    documentclass: scrreprt
    include-in-header:
      - latex_preamble.tex



