# About {.unnumbered}

Welcome to Surface Hydrology (71630) at the Hebrew University of Jerusalem.
This is [Yair Mau](https://yairmau.com), your host for today.
I am a senior lecturer at the Institute of Environmental Sciences, at the Faculty of Agriculture, Food and Environment, in Rehovot, Israel.

This website contains (almost) all the material you'll need for the course. If you find any mistakes, or have any comments, please email me.

## Syllabus

### Course description

This is an introductory course in Surface Hydrology, dealing with some of the major processes in the hydrologic cycle: precipitation, evaporation and transpiration, infiltration, runoff generation and streamflow. The different topics will be treated using mathematical models and practical programming exercises.

### Course aims

The course aims at giving the students a quantitative understanding of the main processes in the hydrologic cycle. We will characterize the hydrologic cycle and its fluxes through mass balance equations. The random nature of the various processes will be studied with statistics, time series analysis, return periods, extreme value distributions, etc. We will take a “hands-on approach”, where students will actively engage with the material by analysing data and writing models using Python.

### Learning outcomes

On successful completion of this module, students should be able to:

* Identify the various components of hydrologic budget and their interdependency. 
* Describe the various processes in hydrology (precipitation, infiltration, evaporation, etc) in a mathematical language. 
* Write computer code to analyze the statistics of hydrologic fluxes, and construct models of hydrological systems.

### Books and other sources 

* Dingman, S. L. (2015). Physical hydrology (3rd edition). Waveland press. 
* Ward, A. D., & Trimble, S. W. (2003). Environmental hydrology. CRC Press.
* Brutsaert, W. (2005). Hydrology: An Introduction. Cambridge University Press.

### Course evaluation

There will be some small projects during the semester, all worth 50% of the grade. A final and larger project (50% of the grade) will be due at the end of the semester. All projects will be done in Python (on Jupyter Notebooks).