---
title: "Final Assignment 2025"
# execute:
#   freeze: auto  # re-render only when source changes
# jupyter: python3
---

## 📒 instructions
This is where learning happens, not during a lecture. You'll learn a ton of things by doing them yourself. Much success! 😄

You will hand in a Jupyter Notebook with all your code, and a report in pdf format with text and figures:

1. `assignment-FINAL-CODE-IDNUMBER.ipynb`, and
2. `assignment-FINAL-REPORT-IDNUMBER.pdf`,

where `IDNUMBER` is your 9-digit ID.

Make a zip file that includes these files and **any other data** needed to run your code (e.g. csv files).


## 📌 locations and data

**Choose one location in the US.**

Download relevant data from NOAA's [Global Summary of the Month](https://gis.ncdc.noaa.gov/maps/ncei/cdo/monthly),  NOAA's [Climate Reference Network Data](https://www.ncdc.noaa.gov/crn/qcdatasets.html), and from the USGS's [National Water Information System](https://maps.waterdata.usgs.gov/mapper/index.html).

Try to find locations with many years of data, the more the better. Take some time to choose your station, plan well. **Choose a location you have not worked with in past assignments.**

There is nothing special about the USA, it's just that we have easy access to good quality data. If you have access to equally good data from other countries, you can use it as well.

When you submit your report, don't forget to include all the necessary `csv` files, we will not download the data ourselves.

## 🛠 tasks

In this final project, we will integrate the various topics we learned throughout the semester. You will **tell a story** about the location you chose, and describe the changes it experienced in the past many decades. You can focus on any kind of changes that would influence the hydrological fluxes we learned about. Here are a few examples of changes that you might work on:

* severe droughts in part of the studied period, or an increasing trend in drought severity.
* same as above for rainfall/floods, high temperatures, low temperatures, etc.
* significant changes in land use, such as urbanization, deforestation, agricultural practices, etc.

The list above is not comprehensive, you can choose other factors.

<div class="alert alert-danger">
**IMPORTANT:**

You will have to formulate a hypothesis or to clearly state your expectations regarding the changes in the hydrological cycle.

For example, it is **not ok** to write "I will check if the construction of the dam in this river changed the streamflow characteristics." The hydrological cycle changes all the time, you are guaranteed to find "changes". Instead, I want you to tell me what kind of changes you would expect. You might say, "extreme floodings are less likely after the dam construction, because..."
</div>

Find in scientific papers evidence for the change you are focusing on. **Cite at least one** peer-reviewed scientific paper.

Can you see the same when analyzing data for the location you chose? Do your findings corroborate the expectation you had when you started this project? If they don't, can you explain why? Did you reach interesting or surprising conclusions in your analysis?

<div class="alert alert-info">
**Obligatory part:**
Analyze your location's history with respect to the following:

* Precipitation: seasonality, inter-annual variability, extreme precipitation events and return periods.
* Potential evapotranspiration: Calculate PET using Penman's equation for at least 5 different years of interest (not necessarily contiguous years).

</div>

**Try to connect the dots:** how do your different findings fit together? Discuss what you are trying to show, tell your story with the help of the data and your analyses. If you find things that go contrary to your expectations, can you raise hypotheses of why you see what you see?

## report proposal

You will write your idea for your final project in one half or one third of a page, and submit it on moodle. The deadline is July 6, 2024. You will **NOT** be able to submit your final report if you haven't received an email by me saying that I approve your project idea.

## 🌅 presentation
All the assignment must be in one Jupyter Notebook for the code, and a report in pdf format for text and figures.

The notebook called `CODE` will contain all the code for the analyses you made. It must be **fully functional**, i.e., we must be able to `Run All` and not get any errors. Explain what you are doing in each step. Comment your code. Use markdown cells to split the notebook into subsections, one for each analysis (e.g.: `## Precipitation Analysis`, `### Inter-annual variability`, etc).

The pdf document called `Report` will contain graphs and relevant data from the `CODE` notebook. It is here where you will introduce the location you chose, what you are trying to see. Here you will write all the results and discussion, as supported by the graphs and results you produced. Divide this notebook into sections: Introduction, Results and Discussion, Conclusion. Subdivide the sections into subsections when needed. In this file there should be no code at all.

## 🔜 deadline

The submission deadline is July 31, 2025. You should **not** hand in a dry report: I'm expecting some text before and after each code/graph cell explaining what you did, why you did it, and how it fits the story you are telling. Don't forget to put labels on your plot axes, title, legend, etc.  Please refer to the main [Assignments page](/assignments/assignments-instructions.qmd) for more details on how to write this report.

Your Jupyter Notebook should be **fully functional**: if we press `Kernel > Restart & Run All`, all the code must work without any errors.